format_version: 3
pipelines:
  gocd-test:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/yanggongbi/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - war-builder:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_war_builder:
            timeout: 0
            artifacts:
            - build:
                source: '**/*.war'
                destination: ''
            tasks:
            - exec:
                command: ./build_war_builder.sh
                working_directory: helloworld-war/war_builder
                run_if: passed
            - exec:
                command: ./build_war.sh
                working_directory: helloworld-war
                run_if: passed
